display_name: VPN4ยง
url: https://github.com/almaziphone/magnitvpntv
license: Other

packager: MagnitVPN Team
packagerEmail: linux@magnitvpn.com

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/source/ic_launcher_border.png

keywords:
  - MagnitVPNTV
  - Proxy
  - VPN
  - V2ray
  - Nekoray
  - Xray
  - Psiphon
  - OpenVPN

generic_name: MagnitVPNTV

group: Applications/Internet

startup_notify: true
