display_name: MagnitVPNTV
package_name: magnitvpntv
maintainer:
  name: MagnitVPN Team
  email: linux@vpn5tv.com

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/source/ic_launcher_border.png

postinstall_scripts:
  - echo "Installed MagnitVPNTV"
postuninstall_scripts:
  - echo "Surprised Why?"

keywords:
  - MagnitVPNTV
  - Proxy
  - VPN
  - V2ray
  - Nekoray
  - Xray
  - Psiphon
  - OpenVPN

generic_name: MagnitVPNTV

categories:
  - Network

startup_notify: true
